services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 10s
      retries: 5

  airflow-webserver:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/opt/airflow
      # Пробрасываем папку с профилями из твоего домашнего каталога в контейнер
      - ${HOME}/.dbt:/home/airflow/.dbt
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Указываем dbt искать профиль именно в домашней папке контейнера
      - DBT_PROFILES_DIR=/home/airflow/.dbt
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/opt/airflow
      - ${HOME}/.dbt:/home/airflow/.dbt
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - DBT_PROFILES_DIR=/home/airflow/.dbt
    command: scheduler